# Generated by Django 3.1.3 on 2021-06-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_String_Handling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_letters_set', models.CharField(max_length=50, verbose_name='letters')),
                ('min_number_letters_in_word', models.IntegerField(verbose_name='minimum')),
                ('max_number_letters_in_word', models.IntegerField(verbose_name='maximum')),
                ('word_variants', models.TextField(verbose_name='variants')),
            ],
        ),
    ]
